services:
  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  quarkus-mcp-server:
    image: ghcr.io/2425-5bhif-wmc/03-tutorials-marksuus/quarkus-mcp-server:latest
    container_name: quarkus-mcp
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-db:5432/db
      QUARKUS_DATASOURCE_USERNAME: app
      QUARKUS_DATASOURCE_PASSWORD: app
